from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path

import httpx

GITHUB_API = "https://api.github.com"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--diff", required=True)
    parser.add_argument("--score", required=True)
    parser.add_argument("--report", required=True)
    parser.add_argument("--workspace", required=True)
    args = parser.parse_args()

    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    base_ref = os.environ.get("GITHUB_BASE_REF") or os.environ.get("GITHUB_REF_NAME") or "main"
    head_ref = os.environ.get("GITHUB_HEAD_REF") or os.environ.get("GITHUB_REF_NAME") or base_ref
    pr_number = os.environ.get("GITHUB_PR_NUMBER") or _extract_pr_number()

    if not token or not repo:
        print("::warning::GITHUB_TOKEN or GITHUB_REPOSITORY missing; skipping PR open", file=sys.stderr)
        return 0

    diff_text = Path(args.diff).read_text(encoding="utf-8")
    if not diff_text.strip():
        print("Diff is empty; skipping PR open", file=sys.stderr)
        return 0

    workspace = Path(args.workspace)
    branch = f"brief/auto-update-{int(time.time())}"

    print(f"Creating branch {branch} from {base_ref}", file=sys.stderr)
    _git(workspace, "config", "user.name", "brief-bot")
    _git(workspace, "config", "user.email", "brief-bot@users.noreply.github.com")
    _git(workspace, "checkout", "-b", branch)
    apply_result = subprocess.run(
        ["git", "apply", "--whitespace=nowarn", args.diff],
        cwd=workspace,
        capture_output=True,
        text=True,
    )
    if apply_result.returncode != 0:
        print(f"::warning::git apply failed: {apply_result.stderr.strip()}", file=sys.stderr)
        return 0

    _git(workspace, "add", "-A")
    _git(workspace, "commit", "-m", f"Brief: agent-readiness improvements (score {args.score}/100)")

    remote_url = f"https://x-access-token:{token}@github.com/{repo}.git"
    _git(workspace, "push", remote_url, f"HEAD:refs/heads/{branch}")

    pr = _create_pr(
        token=token,
        repo=repo,
        head=branch,
        base=base_ref,
        score=args.score,
        report_path=args.report,
    )
    if pr is None:
        return 0

    new_pr_number = pr["number"]
    print(new_pr_number)

    if pr_number:
        _comment_on_original(
            token=token,
            repo=repo,
            pr_number=pr_number,
            new_pr_number=new_pr_number,
            score=args.score,
        )
    return 0


def _git(cwd: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True)


def _extract_pr_number() -> str | None:
    ref = os.environ.get("GITHUB_REF", "")
    parts = ref.split("/")
    if "pull" in parts:
        idx = parts.index("pull")
        if idx + 1 < len(parts):
            return parts[idx + 1]
    return None


def _create_pr(
    token: str,
    repo: str,
    head: str,
    base: str,
    score: str,
    report_path: str,
) -> dict | None:
    body = (
        f"## Brief — Agent-Readiness Audit\n\n"
        f"**Current score:** {score} / 100\n\n"
        f"This PR proposes description changes that Brief generated for saved searches "
        f"missing documentation. Applying the diff brings the app closer to "
        f"AI-agent-callable status.\n\n"
        f"- Each `description = ...` insert was generated from the SPL's structure "
        f"(indexes, sourcetypes, fields, transformations) — not from the search name.\n"
        f"- The full HTML report is available as a workflow artifact (`report.html`).\n"
        f"- The MCP manifest (`mcp_manifest.yaml`) declares which searches are safe "
        f"for AI agents to call.\n\n"
        f"_Generated by [Brief](https://github.com/{repo})._"
    )
    response = httpx.post(
        f"{GITHUB_API}/repos/{repo}/pulls",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        json={
            "title": f"Brief: agent-readiness improvements (score {score}/100)",
            "head": head,
            "base": base,
            "body": body,
        },
        timeout=30,
    )
    if response.status_code >= 300:
        print(
            f"::warning::PR creation failed ({response.status_code}): {response.text[:200]}",
            file=sys.stderr,
        )
        return None
    return response.json()


def _comment_on_original(
    token: str,
    repo: str,
    pr_number: str,
    new_pr_number: int,
    score: str,
) -> None:
    body = (
        f"**Brief score:** {score}/100. "
        f"See follow-up #{new_pr_number} for proposed description improvements."
    )
    response = httpx.post(
        f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        json={"body": body},
        timeout=30,
    )
    if response.status_code >= 300:
        print(
            f"::warning::comment on PR failed ({response.status_code}): {response.text[:200]}",
            file=sys.stderr,
        )


if __name__ == "__main__":
    raise SystemExit(main())
